### ISSUE TITLE
Не отображаются графики на главной странице

### ISSUE THREAD

**Issue by VadimFarutin** [RamSaw/CryptoGlass#2]
Шаги воспроизведения:
Открыть главную страницу

Контекст:
Mozilla Firefox 51.5 Windows 8.1

Версия:
0.75

Ожидаемое поведение:
В верхнем правом углу графики

Реальное поведение:
На месте графиков пустое место

**Comment by VadimFarutin** [comment]
Начал работу

**Comment by VadimFarutin** [comment]
fixed

**Comment by vladimirrim** [comment]
Verified all working.
