### ISSUE TITLE
Add sign out button

### ISSUE THREAD

**Issue by vladimirrim** [RamSaw/CryptoGlass#5]
Now users cannot sign out from account. Please, add this functionality.

**Comment by VadimFarutin** [comment]
I'm on it

**Comment by VadimFarutin** [comment]
Done

**Comment by vladimirrim** [comment]
Button isn't in the right place according to the planned web design. Please, correct it

**Comment by VadimFarutin** [comment]
Okay

**Comment by VadimFarutin** [comment]
fixed, button is in the right place

**Comment by vladimirrim** [comment]
but it is supposed to in left place =DDDD
ok, approved
